version: "3.4"

services:
  EasyChefAPI:
    image: easy-chef-api
    build:
      context: .
      dockerfile: EasyChefAPI/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      AppSettings__ConnectionString: ${AppSettings__ConnectionString}
      AppSettings__JWTSecret: ${AppSettings__JWTSecret}
    ports:
      - 3000:3000
