# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  EasyChefAPI:
    image: EasyChefAPI
    build:
      context: .
      dockerfile: EasyChefAPI/Dockerfile
    environment:
    ports:
      - 3000:3000
