//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCutting.Utils {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Utils.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar a mesa!.
        /// </summary>
        public static string ErroAtualizarMesa {
            get {
                return ResourceManager.GetString("ErroAtualizarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar o pedido!.
        /// </summary>
        public static string ErroAtualizarPedido {
            get {
                return ResourceManager.GetString("ErroAtualizarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível buscar os ingredientes!.
        /// </summary>
        public static string ErroBuscarIngredientes {
            get {
                return ResourceManager.GetString("ErroBuscarIngredientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível buscar as mesas!.
        /// </summary>
        public static string ErroBuscarMesas {
            get {
                return ResourceManager.GetString("ErroBuscarMesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível buscar os pedidos!.
        /// </summary>
        public static string ErroBuscarPedido {
            get {
                return ResourceManager.GetString("ErroBuscarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível buscar os perfis!.
        /// </summary>
        public static string ErroBuscarPerfis {
            get {
                return ResourceManager.GetString("ErroBuscarPerfis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível buscar as receitas!.
        /// </summary>
        public static string ErroBuscarReceitas {
            get {
                return ResourceManager.GetString("ErroBuscarReceitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível buscar unidade de medida!.
        /// </summary>
        public static string ErroBuscarUnidadeMedida {
            get {
                return ResourceManager.GetString("ErroBuscarUnidadeMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar o ingrediente!.
        /// </summary>
        public static string ErroCriarIngrediente {
            get {
                return ResourceManager.GetString("ErroCriarIngrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar a mesa!.
        /// </summary>
        public static string ErroCriarMesa {
            get {
                return ResourceManager.GetString("ErroCriarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar o pedido!.
        /// </summary>
        public static string ErroCriarPedido {
            get {
                return ResourceManager.GetString("ErroCriarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar a receita!.
        /// </summary>
        public static string ErroCriarReceita {
            get {
                return ResourceManager.GetString("ErroCriarReceita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar o ingrediente!.
        /// </summary>
        public static string ErroEditarIngrediente {
            get {
                return ResourceManager.GetString("ErroEditarIngrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar a receita!.
        /// </summary>
        public static string ErroEditarReceita {
            get {
                return ResourceManager.GetString("ErroEditarReceita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar a unidade de medida!.
        /// </summary>
        public static string ErroEditarUnidadeMedida {
            get {
                return ResourceManager.GetString("ErroEditarUnidadeMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este endereço de e-mail não está sendo utilizado!.
        /// </summary>
        public static string ErroEmailNaoCadastrado {
            get {
                return ResourceManager.GetString("ErroEmailNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha inválidos!.
        /// </summary>
        public static string ErroEmailSenha {
            get {
                return ResourceManager.GetString("ErroEmailSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este endereço de e-mail já está sendo utilizado!.
        /// </summary>
        public static string ErroEmailUtilizado {
            get {
                return ResourceManager.GetString("ErroEmailUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar o arquivo!.
        /// </summary>
        public static string ErroEnviarArquivoS3 {
            get {
                return ResourceManager.GetString("ErroEnviarArquivoS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível realizar o login!.
        /// </summary>
        public static string ErroLogin {
            get {
                return ResourceManager.GetString("ErroLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum perfil foi encontrado!.
        /// </summary>
        public static string ErroNenhumPerfilEncontrado {
            get {
                return ResourceManager.GetString("ErroNenhumPerfilEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O perfil indicado não existe!.
        /// </summary>
        public static string ErroPerfilNaoExiste {
            get {
                return ResourceManager.GetString("ErroPerfilNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível registrar o usuário!.
        /// </summary>
        public static string ErroRegistrarUsuario {
            get {
                return ResourceManager.GetString("ErroRegistrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível redefinir sua senha!.
        /// </summary>
        public static string FalhaEsqueciSenha {
            get {
                return ResourceManager.GetString("FalhaEsqueciSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma receita foi encontrada!.
        /// </summary>
        public static string FalhaNenhumaReceitaEncontrado {
            get {
                return ResourceManager.GetString("FalhaNenhumaReceitaEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum ingrediente foi encontrado!.
        /// </summary>
        public static string FalhaNenhumIngredienteEncontrado {
            get {
                return ResourceManager.GetString("FalhaNenhumIngredienteEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma mesa foi encontrada!.
        /// </summary>
        public static string FalhaNenhumMesaEncontrado {
            get {
                return ResourceManager.GetString("FalhaNenhumMesaEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum pedido foi encontrado!.
        /// </summary>
        public static string FalhaNenhumPedidoEncontrado {
            get {
                return ResourceManager.GetString("FalhaNenhumPedidoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma unidade de medida foi encontrada!.
        /// </summary>
        public static string FalhaNenhumUnidadeMedidaEncontrada {
            get {
                return ResourceManager.GetString("FalhaNenhumUnidadeMedidaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token informado expirou!.
        /// </summary>
        public static string FalhaTokenExpirou {
            get {
                return ResourceManager.GetString("FalhaTokenExpirou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token informado não existe!.
        /// </summary>
        public static string FalhaTokenNaoExiste {
            get {
                return ResourceManager.GetString("FalhaTokenNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token informado já foi utilizado!.
        /// </summary>
        public static string FalhaTokenUtilizado {
            get {
                return ResourceManager.GetString("FalhaTokenUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este usuário não tem acesso a empresa!.
        /// </summary>
        public static string FalhaUsuarioAcessoEmpresa {
            get {
                return ResourceManager.GetString("FalhaUsuarioAcessoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mesa atualizada com sucesso!.
        /// </summary>
        public static string SucessoAtualizarMesa {
            get {
                return ResourceManager.GetString("SucessoAtualizarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido atualizado com sucesso!.
        /// </summary>
        public static string SucessoAtualizarPedido {
            get {
                return ResourceManager.GetString("SucessoAtualizarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingrediente criado com sucesso!.
        /// </summary>
        public static string SucessoCriarIngrediente {
            get {
                return ResourceManager.GetString("SucessoCriarIngrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mesa criada com sucesso!.
        /// </summary>
        public static string SucessoCriarMesa {
            get {
                return ResourceManager.GetString("SucessoCriarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido criado com sucesso!.
        /// </summary>
        public static string SucessoCriarPedido {
            get {
                return ResourceManager.GetString("SucessoCriarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Receita criada com sucesso!.
        /// </summary>
        public static string SucessoCriarReceita {
            get {
                return ResourceManager.GetString("SucessoCriarReceita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade de medida criada com sucesso!.
        /// </summary>
        public static string SucessoCriarUnidadeMedida {
            get {
                return ResourceManager.GetString("SucessoCriarUnidadeMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingrediente atualizado com sucesso!.
        /// </summary>
        public static string SucessoEditarIngrediente {
            get {
                return ResourceManager.GetString("SucessoEditarIngrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Receita atualizada com sucesso!.
        /// </summary>
        public static string SucessoEditarReceita {
            get {
                return ResourceManager.GetString("SucessoEditarReceita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade de medida atualizada com sucesso!.
        /// </summary>
        public static string SucessoEditarUnidadeMedida {
            get {
                return ResourceManager.GetString("SucessoEditarUnidadeMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi enviado um link para redefinir sua senha no e-mail informado!.
        /// </summary>
        public static string SucessoEsqueciSenha {
            get {
                return ResourceManager.GetString("SucessoEsqueciSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login realizado com sucesso!.
        /// </summary>
        public static string SucessoLogin {
            get {
                return ResourceManager.GetString("SucessoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha redefinida com sucesso!.
        /// </summary>
        public static string SucessoRedefinirSenha {
            get {
                return ResourceManager.GetString("SucessoRedefinirSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário registrado com sucesso!.
        /// </summary>
        public static string SucessoRegistrarUsuario {
            get {
                return ResourceManager.GetString("SucessoRegistrarUsuario", resourceCulture);
            }
        }
    }
}
